### ISSUE TITLE
windows 部署下  pnpm run dev 卡在 Running seed command `ts-node prisma/seed.ts` ...

### ISSUE THREAD

**Issue by Sayyiku** [meetqy/eagleuse#60]
node version 16.19.0  
npm 8.19.3
pnpm 7.26.2 

![image](https://user-images.githubusercontent.com/77047823/215786811-93ef1437-5f31-47b3-8edc-b8cde0f5592a.png)

.env配置
![image](https://user-images.githubusercontent.com/77047823/215787112-dc72497f-1a61-4258-9d2a-21a2ef6b51b6.png)

**Comment by meetqy** [comment]
db:init 初始化没。

还是有问题话，明天我找一台Windows测试一哈。

今天刚用一台新的Linux从零部署了一次，没有发现问题😂

**Comment by Sayyiku** [comment]
初始化了，没问题 
我拉取新版本之后，卡在了新的 **[22:50:27.334] INFO (22036): watching image ...** 上
![image](https://user-images.githubusercontent.com/77047823/215793612-7a2fcf8f-03e3-4630-b0ae-98dc0846174e.png)
我明天拿mac跑一下试试

**Comment by meetqy** [comment]
开两个终端试试

一个执行`pnpm run db:watch`
一个执行`npx next`

**Comment by Sayyiku** [comment]
## npx next
![image](https://user-images.githubusercontent.com/77047823/215796561-e175a842-9bf5-4733-9a4e-cdb150b1b5ae.png)

## pnpm run db:watch
![image](https://user-images.githubusercontent.com/77047823/215796732-71d3f728-0aab-4787-83e3-20871179e9a3.png)

**Comment by Sayyiku** [comment]
貌似是window终端默认没有以管理员身份启动导致没有权限无法访问library下的文件
