### ISSUE TITLE
windows部署报错 Error: absolute srcpath does not exist

### ISSUE THREAD

**Issue by AceCandy** [meetqy/eagleuse#75]
``拉取的最新0.1.7代码进行部署，根据readme执行命令pnpm run dev时会报错：
<img width="1278" alt="111" src="https://user-images.githubusercontent.com/6278583/217517819-a6ae1c07-03af-4eea-acf0-63aef5c46665.png">

一开始是报错：'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
然后百度之后在命令前加上了cross-env进行执行，这次不报NODE_ENV了，报了Error: absolute srcpath does not exist错误。

之前看过其它issue有说权限问题的，但是我用的是管理员启动的powerShell。另外附上我的.env文件配置，帮忙看看是不是我配置错误的问题。

```
# eagle library地址
LIBRARY=C:\Users\AceCandy\Pictures\eagleuse
# 数据库地址
DATABASE_URL=file:${LIBRARY}/eagleuse.db?connection_limit=1
# 监听手动替换 eagleuse.db，无需重启服务器，当执行 db:watch 时，会自动赋值为false
WATCH_REPLACE_DATABASE_FILE=true
# 菜单是否显示回收站
SHOW_TRASH=true
```

**Comment by meetqy** [comment]
老家你eagle library喃，正常来说eagle的library应该是.library结尾的

**Comment by meetqy** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/18411315/217523869-2bb69ce8-f921-40a3-9f13-a9801b2144f4.png">
<img width="695" alt="image" src="https://user-images.githubusercontent.com/18411315/217523954-b93bb5f6-4815-4e5a-b048-b1ab19611740.png">

**Comment by AceCandy** [comment]
大概了解了，原来是得基于eagle这个应用，我以为是单独的自建图床。。
